# Generated by Django 4.0.6 on 2022-07-24 20:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcontentitem',
            name='szContentSlug',
            field=models.SlugField(help_text='Слаг  (транслитерация) контента', max_length=255, unique=True, verbose_name='slud'),
        ),
        migrations.AlterField(
            model_name='tbcontentitem',
            name='szContentText',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Содержание <b>БЕЗ АНОНСА</b> <small>(допустим HTML-код, будет обработан типографом, если его включить)</small>', verbose_name='Содержание'),
        ),
    ]
